name: Slack Notification

on:
  push:
    tags:
    - '*'

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Release notification
        uses: stormwarning/action-release-notification@v1
        with:
          channel: noa.avidar
          message: A new version is out!
        env:
          SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
