name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get latest tag'
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"



      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "CTP Deployment",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New Release deployed to ${{ github.ref_name }}! $(git log -1 --pretty=%B) "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#todo: change channel in the workfow and here: "https://api.slack.com/apps/A04DEVBD3B9/incoming-webhooks?"
# add SLACK_WEBHOOK secret: copy uri from same link

# https://github.com/zoomin-software/portal-theme/actions/workflows/ontag.yml
#