name: Slack Notification

on:
  push:
    tags:
    - '*'

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get latest tag'
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: noa.avidar
          SLACK_TITLE: 'CTP ${{ steps.get-latest-tag.outputs.TAG }} is being released! :rocket: '
          SLACK_MESSAGE:
           'changelog :point_right:
           https://github.com/zoomin-software/pdfqueuer-ng/releases/tag/${{ steps.get-latest-tag.outputs.TAG }}'
          SLACK_USERNAME: ctp-bot
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

#todo: change channel in the workfow and here: "https://api.slack.com/apps/A04DEVBD3B9/incoming-webhooks?"
# add SLACK_WEBHOOK secret: copy uri from same link

# https://github.com/zoomin-software/portal-theme/actions/workflows/ontag.yml